name: Build

on:
  push: {branches: [main]}
  pull_request: {branches: [main]}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo clippy --release
    - run: cargo test --release
    - run: cargo install cross
    - run: cross build --release --target x86_64-unknown-linux-musl
    - run: cross build --release --target x86_64-apple-darwin
    - run: cross build --release --target x86_64-pc-windows-gnu
    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/head/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        files: |
          LICENSE
          target/x86_64-unknown-linux-musl/release/hype
          target/x86_64-apple-darwin/release/hype
          target/x86_64-pc-windows-gnu/release/hype.exe
