name: Build

on:
  push: {branches: [main]}
  pull_request: {branches: [main]}

env: {CARGO_TERM_COLOR: always}

jobs:
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: hype-mac
        path: target/release/hype
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: hype.exe
        path: target/release/hype.exe
  build:
    needs: [mac, windows]
    runs-on: ubuntu-latest
    steps:
    - run: rustup target add x86_64-unknown-linux-musl
    - uses: actions/checkout@v2
    - run: cargo clippy --release
    - run: cargo test --release
    - run: cargo build --release --target x86_64-unknown-linux-musl
    - uses: actions/upload-artifact@v2
      with:
        name: hype
        path: target/x86_64-unknown-linux-musl/release/hype
    - uses: actions/download-artifact@v2
      with: {name: hype-mac}
    - uses: actions/download-artifact@v2
      with: {name: hype.exe}
    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        files: |
          LICENSE
          target/x86_64-unknown-linux-musl/release/hype
          hype-mac
          hype.exe
